modified files

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,14 +44,14 @@ jobs:
  
       # Step 6: List dist directory for debugging
       - name: List dist directory
-        run: ls -alh /build || echo "Dist directory not found"
+        run: ls -alh /dist || echo "Dist directory not found"
  
       # Step 7: Deploy to Netlify (dev branch)
       - name: Deploy to Netlify (dev)
         if: github.ref == 'refs/heads/dev'
         uses: nwtgck/actions-netlify@v3
         with:
-          publish-dir: ./build
+          publish-dir: ./dist
           production-deploy: false
         env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
@@ -68,7 +68,7 @@ jobs:
           password: ${{ secrets.SMTP_PASSWORD }}  # App password
           subject: "Code Deployed to Dev Environment"
           body: "The latest code has been successfully deployed to the dev environment. Visit the site at ${{ secrets.HOMEPAGE_URL }}."
-          to: "srikarvanaparthy21@gmail.com"
+          to: "gogulateja92@gmail.com"
           from: "gogulanavateja1910@gmail.com"
  
  
@@ -89,12 +89,14 @@ jobs:
           base: prod
           title: "Pull Request: Merge Dev into Prod"
           body: "This pull request is for merging the changes from the dev branch to the prod branch."
+          auto-merge: false  # Ensure the pull request is not merged automatically
+         
+ 
  
   deploy-to-netlify-prod:
     name: Deploy to Netlify (Prod)
     runs-on: ubuntu-latest
     needs: create-pull-request  # This ensures the deploy happens after the PR creation
-    if: github.ref == 'refs/heads/prod' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
     steps:
       # Step 1: Checkout Code
       - name: Checkout Code
@@ -116,7 +118,7 @@ jobs:
       - name: Deploy to Netlify (Prod)
         uses: nwtgck/actions-netlify@v3
         with:
-          publish-dir: ./build
+          publish-dir: ./dist
           production-deploy: true
         env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
@@ -131,7 +133,7 @@ jobs:
           server_port: 587
           username: ${{ secrets.SMTP_USERNAME }}  # Your Gmail address
           password: ${{ secrets.SMTP_PASSWORD }}  # App password
-          subject: "Code Deployed to Dev Environment"
-          body: "The latest code has been successfully deployed to the dev environment. Visit the site at ${{ secrets.HOMEPAGE_URL }}."
-          to: "srikarvanaparthy21@gmail.com"
+          subject: "Code Deployed to Prod Environment"
+          body: "The latest code has been successfully deployed to the prod environment. Visit the site at ${{ secrets.PROD_HOMEPAGE_URL }}."
+          to: "gogulateja92@gmail.com"
           from: "gogulanavateja1910@gmail.com"
